export const imagesUrls = [
  '5CzRvULn8HXpmSuETprL.jpg',
  '9hrkbWbu34JMwRR4iQzs.jpg',
  'd8PqssQDWK1QB7lwqZkv.jpg',
  'EBupgrN1lD7ojRF6dGUq.jpg',
  'HrebSgUn2Pgt1rBtlTVZ.jpg',
  'HSVT9kNrf8CX2ztDfHcV.jpg',
  'K71B9HdHyPAmohRC3oQO.jpg',
  'MBCORDHP0YrDZnJ1hys7.jpg',
  'nPFJ1CU3GCwqYJnpN5HD.jpg',
  'R4uSPVj6xA6ooECTKoIB.jpg',
  'tXIecfLe0aQRsDCJSEYu.jpg',
  'vcWxXDR3YvbuGUWXrTem.jpg',
  'wiOWwAFIAhCiPV8VDDhQ.jpg',
  'YMNf0TIVFL2LiJHabWDt.jpg',
]
