export const phrases = [
  'Huevon, acabo de escuchar magia en mi cuarto.',
  'En esta vida todos tenemos un engranaje que cumplir.',
  'Que fue ese sonido huevon, fue como una foca muriendo. "tun-tun".',
  'Preguntan: Gnomo, por qué los hombres tienen pezones? Gnomo: Tanto los hombres como los ratones[...] Lo saqué de ojo curioso.',
  'Mi mamá es un AD carry.',
  'Garen y sus métodos arcaicos de matar todavia funcan, men.',
  'El presidente esta encerrado.',
  'Ves, ves, no me hicieron nada.',
  'El trompito... Girasol.',
  'Te imaginas si Sharknado fuera real? Y en vez de tiburones sean cactuses y estes caminando por ahi y te caiga uno en la cara?',
  'Sabes con que se peuden lanzar los cohetes? Con un lanzacohetes.',
  'Te imaginas tener un rinoceronte de amigo?',
  'Antes la tierra estaba poblada por árboles.',
  'Si amarras una madera a tu llanta, tienes mas tracción.',
  'Las ranas sueñan con ser challenger, pero luego despiertan.',
  'El niñito le queria tirar una torta a la anciana.',
  'Un tiburón se esta ahogando en el aire.',
  'El éxito es como la cebolla, capa por capa.',
  'Si tuvieras una vaca voladora, ¿la ordeñarías en el aire o esperarías a que aterrizará primero?',
  'La lluvia huele a perro mojado.',
]
